### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Nightsquid7** [Nightsquid7/CEN-4020-Group-Project#18]
## Bullets
 - [x] make bullets move in direction of crosshair
 - [x] make bullets disapear when they hit a 2D 
 - [x] crosshair sprite
 - [ ] add explosion response to a hit
### All
 - [x] add triggers to move character to next level
 - [x] re-add box collider to level 1 trigger
 - [ ] add at least four rooms to each level, except into level
 - [x] level transitions updating player and stats
 - [ ] obstacles/ lamps to rooms ??? 

### 1
 - [ ] add animation to the door so it opens

## Artifacts
 - [x] create coins/jewels/potions
 - [x] animate them
 - [x] interact with players for pickups
 - [x] update player stats according to pickups

#### Player
 - [x] add collision detection
 - [x] add interactions with artifacts
 - [x] add walking movements
 - [ ] add response to bullets...hit/harm/death reactions
 - [x] add animations

 #### Enemies
- [x] add collision detection
- [x] add AI search toward player
- [ ] add response to bullets...hit/harm/death reaction
- [ ] add AI defense movements toward bullets (dodge effect?)
- [x] determine shooting scheme...time delay/ player position to trigger fire?
- [x] determine various movements per type of enemy/boss
- [ ] movement animations

## Weapons
 - [x] create weapon sprites
 - [x] each weapon has its own AI firing mechanism

## Menu
 - [x] intro storyline frame
 - [x] scoring, updating player/enemy values
 - [x] pause button in levels, brings up menu
 - [x] instruction menu

## Sounds
 - [x] background theme
 - [x] sounds for doors, projectile hits, artifact pickups

## Questions
- [x]  Do we create a new player object for every new scene, or do we share player objects across scenes? 
(if we create a new one we need to instantiate all his attributes with the current ones, health coins etc, probably easier to share, probably easier to just have one big map though in a scene?)
A: We agreed that it seems that same player just transitions to next level taking attributes with him
